<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>   
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>   
	<Product></Product>   
	<Description>Automation run console for EwE</Description>   
	<Company>Ecopath International Initiative</Company>   
	<Authors>JeroenS</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Automation\Ecosim\Functions\MorResponseFunction .cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\Rik\.nuget\packages\eii.ecopath.ewecore\6.7.85\contentFiles\any\net8.0\Includes\Interop.JRO.dll" />
    <Content Remove="C:\Users\Rik\.nuget\packages\eii.ecopath.ewecore\6.7.85\contentFiles\any\net8.0\Includes\Microsoft.Office.interop.access.dao.dll" />
    <Content Remove="C:\Users\Rik\.nuget\packages\eii.ecopath.ewecore\6.7.85\contentFiles\any\net8.0\Resources\LICENSE.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Testdata\AnchovyBay_log.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Eii.Ecopath.Bridge" Version="1.0.5" />
    <PackageReference Include="Eii.Ecopath.EwECore" Version="6.7.85" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Anchovy Bay Spatial.eiixml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBay_runinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\MPA_test.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SampleFile.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBay.eiixml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBay_extdata.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayMPA\mpa_noshrimpers_2005-05.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayMPA\mpa_noshrimpers_2012-09.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayPP\AnchovyBay_RelPP.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayTemperature\sst_2000-01.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayTemperature\sst_2010-01.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayTemperature\sst_2013-01.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayTemperature\sst_2014-07.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Testdata\AnchovyBayTemperature\sst_2019-04.asc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
