<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\EwEDev\.nuget\packages\eii.ecopath.ewecore\6.7.105\contentFiles\any\net10.0\Includes\Interop.JRO.dll" />
    <Content Remove="C:\Users\EwEDev\.nuget\packages\eii.ecopath.ewecore\6.7.105\contentFiles\any\net10.0\Includes\Microsoft.Office.interop.access.dao.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eii.Ecopath.Bridge" Version="1.0.*" />
    <PackageReference Include="Eii.Ecopath.EwECore" Version="6.7.*" />
    <PackageReference Include="Eii.Ecopath.SpatialAssetsEnginePlugin" Version="1.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eii.Ecopath.Runner.Datamodel\Eii.Ecopath.Runner.Datamodel.csproj" />
  </ItemGroup>

</Project>
